image: node:8

release:
  stage: deploy
  script:
  - npm install
  - npm run release
  - ./bin/configure_git_on_gitlab.sh
  - ./bin/release_on_gitlab.sh
  - ./bin/release_on_gitlab_pages.sh
  artifacts:
    paths:
      - public
  only:
  - master
