image: node:8

release:
  stage: deploy
  script:

  - ./bin/release_on_gitlab.sh
  - ./bin/zip_version_gitlab.sh
  - ./bin/release_on_gitlab_pages.sh
  artifacts:
    paths:
      - public
  only:
  - master
