language: node_js
node_js:
- '6.9.2'
env:
  global:
  - GH_REF=github.com/Cloud-Player/web
  - secure: P5ZfYE7E0PRIcFAAS6xu8ISv/AHENqO3Wnyf14xPhrc/fuauf3M3nUWthOVbTtQaUHkwlatZmMVTcq38IQahrBZ+ckPTBQMrlH9Nl/YMrFhxFz/R4Uy9EWhhOrmivsaTVVtM4j2B4hjpa/0vXygcvfPoLkG23KkcEhxj1tmQgXtOUurhKFCAdLPRXg1aMVD+dhBDJTivVrrhJhBz01O+r97KO9y7CAS9t/dt4D9XfSdAiYHfucWENzSWBULBsg0Wso6wybziJ67R/+D1VylWeemBISgnZ0Mj4xIaHzzrkSIQz5cYElesEJRgGn8AaiF3H/JDGkLRw3IwW+z5ZyF/Fsdd4/mQi4Wsm+IK+tUyaFRajZ8dmJKmPjpPzV4KXquF5GTEdsptxT3YSKKlOKzo5glrgZvGic73qTtdS/hruzTbu7vkXY6GptqfHXGw/sNJcYhwro9/YP4DLDYsS99bkq59MuKGVvd1Cfg3Nc3NFCm/xwSwkmDx/7tXSL7Cd145MnbMGo6dPNbgVNw3smDuzPeH1zeWCPPRhpcjCHMvkUoPHyfe3XpegorYtGNtW8uOgkyBMPhGDslqQ4UDx2hE/qPqHWezYVFuiWoxR0HxV2bpBmzTrOzBwu6u9O2Mb+3jbHDCVfjVr0vqb//DxA10hxlWYE/JLFhNuLxJz62K9a0=
before_install:
- npm install -g webpack
before_deploy:
- npm run build
deploy:
  - provider: script
    script: ./bin/github_pages_release.sh
    skip_cleanup: true 
    on: 
      branch: master
