language: node_js
node_js:
- '6.9.2'
env:
  global:
  - GH_REF=github.com/Cloud-Player/cloud-player
  - secure: cymdjTIdXd7IuNpJjNVmHRsEGAwMxxW4laLUqVDkeI2k7DUKAtFhimnKFCFw19W/FfN4Lin2LWLMuT5vqmtNOqClrt1W0vPhseXQckNGBq038iBqUk3Tbnau6xmg28QmDJjGw5N4pvHGaL9LHOnjnXzdQ9vD3PfuIvH8RA2XdzoghA9XG0H90+7RdygUJotDmWx4auMK7LYH8XZCdssox44EsaGr1yy5ldRUeJD9246hvjLYGYum8tr8DyIZecMk+AOXxLDrwfQv9gPVPqR4OLTrY751DAVcOq3Z5hQSDWkOrK3DVm0Rm5nlu3kge9C88QqbACCbjojwK1FpiPh0bOKWvpJT+wsK1rlHcC/ilDhnDDcl18nnn/sXb3VRbYtneV1mlHeaOyej/wzMdNmwxdvCUN1IKdrRUzLsOz2aB98jOlHXz8ZLTE4Cwm44CQe1iPymq18g7bV2G7TrKImXBUJBqeP8LmXRfXPRB12LSldOlOCWfqTRxZ4wrRQcL1pyirx/TqiFSZaYxU5Jupoc+xbv1/cpdgXLWoCbjaBeiO0HtBIsy2UqBKtdky/7XI+uvYfiRQn6NKQ3gfaCHqRHKhQDuPu93lfo3wg7/xsIC5S81uaW0vufPxo1DO2b07h5NKPnSFxnosBak954kNPf3Lxk3Kz468zFtokE9c4pbzA=
before_install:
- npm install -g webpack
before_deploy:
- npm run build
deploy:
  - provider: script
    script: ./bin/github_pages_release.sh
    skip_cleanup: true 
    on: 
      branch: master
